name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    environment: production

    steps: 
      - uses: actions/checkout@v2 
      - run: | 
          npm install
          export DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} 
          pm2 start -f index.js --name Vu-guessing-game-dioscrd-bot      
