name: Node.js CI

on:
  push:
    branches: [ master, file_creation_debug ]
  pull_request:
    branches: [ master, file_creation_debug ]

jobs:
  build:

    runs-on: self-hosted

    steps: 
      - uses: actions/checkout@v2 
      - run: | 
          npm install
          export DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} 
          pm2 start index.js --name Vu-guessing-game-dioscrd-bot
      
